

```{r}

library(tidyverse)

#datafestdata<-readr::read_csv("/Users/rileyboeth/Downloads/Datafest/dataFestReleaseFinal_3_23.csv")

#ggplot(datafestdata, aes(applies))+
#  geom_histogram(bins  = 500)

#ggplot(datafestdata, aes(clicks))+
#  geom_histogram(bins  = 500)


#ggplot(datafestdata, aes(descriptionLengthChars))+
#  geom_histogram(bins  = 500)

```


```{r}
library(rpart)
library(rpart.plot)
train<-datafestdata%>%
  filter(avgoverallcompanyrating != 0)%>%
  slice(1:891975)

test<-datafestdata%>%
  filter(avgoverallcompanyrating !=0)%>%
  slice(891976:1274249)

#linear regression predicting avgoverallcompanyrating
reg1<-lm(avgoverallcompanyrating~descriptionLengthChars+supervisingJob+noEducationRequirementsJob+highSchoolEducationRequirementsJob+higherEducationRequirementsJob+applies+clicks+employeecount+employerIndustry+admin1, data = train)
summary(reg1)

prediction<-  data.frame(prediction = predict(reg1, newdata = na.omit(test)))
test<-na.omit(test)%>%
  bind_cols(prediction)

test<-test%>%
  select(avgoverallcompanyrating,prediction)%>%
  mutate(difference = avgoverallcompanyrating - prediction)

ggplot(test, aes(difference))+
  geom_histogram(bins= 500)


#ratio of number of jobs in area to number of applicants
ratio<-datafestdata%>%
  group_by(admin1,employerIndustry)%>%
  summarise(num_jobs = n_distinct(jobHash), 
            num_applicants = sum(applies),
            num_clicks = sum(clicks, na.rm=TRUE))%>%
  ungroup()%>%
  mutate(ratio_applications_to_jobs = num_applicants/num_jobs,
         ratio_clicks_to_jobs = num_clicks/num_jobs)
```


```{r}
indeed_mini <- readr::read_csv("Indeed_mini.csv")
indeed_full <- readr::read_csv("dataFestReleaseFinal_3_23.csv")
```

```{r}
head(indeed_full)
```

```{r}
indeed_full_edit <- indeed_full 

indeed_full_region <- indeed_full %>%
  group_by(admin1, normtitlecategory) %>%
  summarize(n_jobs = n_distinct(jobHash), n_applicants = sum(applies), age = mean(jobagedays)) %>%
  mutate(ratio = n_jobs/n_applicants) %>%
  arrange(age) %>%
  filter(normtitlecategory == "tech")
head(indeed_full_region)

```


```{r}

indeed_mini <- readr::read_csv("Indeed_mini.csv")
indeed_full <- readr::read_csv("dataFestReleaseFinal_3_23.csv")
state_populations <-readr::read_csv("state_populations.csv")
```

```{r}

#Avg length of posting

indeed_full %>%
  group_by(normtitlecategory) %>%
  summarize(avg_job_length = mean(jobagedays))%>%
  ggplot(aes(y=avg_job_length, x=reorder(normtitlecategory, avg_job_length))) + geom_bar(stat="identity")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1) )

#Total Applicants

indeed_full %>%
  group_by(normtitlecategory) %>%
  summarize(total_applicants = sum(applies)) %>%
  ggplot(aes(x = reorder(normtitlecategory, total_applicants), y = total_applicants)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1) )


#Applicants/day

indeed_full %>%
  group_by(normtitlecategory) %>%
  summarize(avg_applicants = mean(applies)) %>%
  ggplot(aes(x = reorder(normtitlecategory, avg_applicants), y = avg_applicants)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1) )


```


```{r}
indeed_full %>%
  group_by(admin1) %>%
  summarize(total_applications = sum(applies)) %>%
  ggplot(aes(x=reorder(admin1,total_applications), y=total_applications)) + geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

#add info about state populations to actually learn something from this


EastNorthCentral = c("IL", "IN", "MI", "OH", "WI")
WestNorthCentral = c("IA", "KS", "MN", "NE", "ND", "SD")
SouthAtlantic = c("DE", "FL", "GA", "MD", "NC", "SC", "VA", "WV")
EastSouthCentral = c("AL", "KY", "MS", "TN")
WestSouthCentral = c("AR", "LA", "OK", "TX")
Mountain = c("AZ", "CO", "ID", "MT", "NV", "NM", "UT", "WY")
Pacific = c("AK", "CA", "HI", "OR", "WA")
NewEngland = c("CT", "ME", "MA", "NH", "RI", "VT")
MidAtlantic = c("NJ", "NY", "PA")

indeed_full_region <- indeed_full %>%
  mutate(region = ifelse(admin1 %in% EastNorthCentral, "EastNorthCentral", ifelse (admin1 %in% WestNorthCentral, "WestNorthCentral", ifelse(admin1 %in% SouthAtlantic, "SouthAtlantic", ifelse(admin1 %in% EastSouthCentral, "EastSouthCentral", ifelse(admin1 %in% WestSouthCentral, "WestSouthCentral", ifelse(admin1 %in% Mountain, "Mountain", ifelse(admin1 %in% Pacific, "Pacific", ifelse(admin1 %in% NewEngland, "NewEngland", ifelse(admin1 %in% MidAtlantic, "MidAtlantic", "Other"))))))))))


indeed_full_region_pop <- indeed_full_region %>%
  inner_join(state_populations, by = c("admin1" = "State"))



```


```{r}

indeed_full %>%
  group_by(admin1, normtitlecategory) %>%
  summarize(total_app = sum(applies))


indeed_full_region %>%
  group_by(region, normtitlecategory) %>%
  summarize(total_app = sum(applies))

# job applications adjusted for number of people in region

indeed_full_region_pop %>%
  group_by(region, normtitlecategory) %>%
  summarize(num_applicants = sum(applies), num_people = sum(Pop), app_per_1M= (num_applicants/num_people) * 1000000)



#do function to find the jobs with the lowest app per 1m rates
#apply this function to each region
```



```{r}
leastcompjobs <- function(area) {
  indeed_full_region_pop %>%
  filter(region == area) %>%
  group_by(region, normtitlecategory) %>%
  summarize(avg_age = sum(jobagedays)/n_distinct(jobHash), num_jobs = n_distinct(jobHash), app_per_job = sum(applies)/num_jobs) %>%
  summarize() %>%
  arrange(competition) %>%
  head(5)
}


mostcompjobs <- function(area) {
  indeed_full_region_pop %>%
  filter(region == area) %>%
  group_by(region, normtitlecategory) %>%
  summarize(applications_per_1M = (sum(applies)/sum(Pop)) * 1000000) %>%
  arrange(desc(applications_per_1M)) %>%
  head(5)
}
```

```{r}
indeed_full_region <- indeed_full_region %>%
  mutate(education_level = ifelse(noEducationRequirementsJob == 1, 1,
                         ifelse(highSchoolEducationRequirementsJob == 1, 2, 
                         ifelse(higherEducationRequirementsJob == 1, 3, 0))))



#given region, output industry
least_comp_by_region <- function(area, education) {
  age <- indeed_full_region %>%
    group_by(jobHash) %>%
    summarize(age = max(jobagedays))
  indeed_full_region %>%
    filter(region == area, education_level <= education) %>%
    inner_join(age, by = "jobHash") %>%
    group_by(jobHash)%>%
    mutate(age = max(jobagedays))%>%
    ungroup()%>%
    filter(age == jobagedays)%>%
    group_by(normtitlecategory) %>%
    summarize(avg_age = sum(age)/n_distinct(jobHash), app_per_job = sum(applies)/n_distinct(jobHash), comp = app_per_job * (1 / avg_age)) %>%
    arrange(comp) %>%
  head(5)
}

most_comp_by_region <- function(area, education) {
  age <- indeed_full_region %>%
    group_by(jobHash) %>%
    summarize(age = max(jobagedays))
  indeed_full_region %>%
    filter(region == area, education_level <= education) %>%
    inner_join(age, by = "jobHash") %>%
    group_by(jobHash)%>%
    mutate(age = max(jobagedays))%>%
    ungroup()%>%
    filter(age == jobagedays)%>%
    group_by(normtitlecategory) %>%
    summarize(avg_age = sum(age)/n_distinct(jobHash), app_per_job = sum(applies)/n_distinct(jobHash), comp = app_per_job * (1 / avg_age)) %>%
    arrange(desc(comp)) %>%
  head(5)
}




least_comp_by_region(area = "NewEngland", education = 2)
most_comp_by_region(area = "NewEngland", education = 2)




```

```{r}
leastcompjobs("NewEngland")
mostcompjobs("NewEngland")
```

```{r}

regions = c("EastNorthCentral", "WestNorthCentral", "SouthAtlantic", "EastSourthCentral", "WestSouthCentral", "Mountain", "Pacific", "NewEngland", "MidAtlantic", "Other")
most_comp_jobs <- lapply(regions, FUN = mostcompjobs) %>% bind_rows()
least_comp_jobs <- lapply(regions, FUN = leastcompjobs) %>% bind_rows()


most_comp_jobs %>%
  arrange(desc(applications_per_1M))

most_comp_jobs %>%
  arrange(desc(applications_per_1M))
```


```{r}

#density of jobs in a given field by region

regions = c("EastNorthCentral", "WestNorthCentral", "SouthAtlantic", "EastSourthCentral", "WestSouthCentral", "Mountain", "Pacific", "NewEngland", "MidAtlantic", "Other")


most_comp_cities = function(jobfield, state) {
  indeed_full_region_pop %>%
  filter(normtitlecategory == jobfield & admin1 == state) %>%
  group_by(city) %>%
  summarize(numjobs = n(), numapplicants = sum(applies), applications_per_job = numapplicants/numjobs) %>%
  arrange(desc(applications_per_job)) %>%
  head(10)
}


most_comp_cities("techsoftware", "CA")

least_comp_cities = function(jobfield, state) {
  indeed_full_region_pop %>%
  filter(normtitlecategory == jobfield & admin1 == state) %>%
  group_by(city) %>%
  summarize(numjobs = n(), numapplicants = sum(applies), applications_per_job = numapplicants/numjobs) %>%
  arrange(applications_per_job) %>%
  head(10)
}

least_comp_cities("techsoftware", "CA")
```


